management:
  endpoints:
    web:
      exposure:
      include: '*'
  info:
    env:
      enabled: true

info:
  application:
    name: CapstoneHotels
    description: An hotel website where guest can make room reservation
    author: PerryJay
    version: '@project.version@'
spring:
  profiles:
    active: prod

