spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}
      password: ${MONGODB_PASSWORD}
      port: ${MONGODB_PORT}
      host: ${MONGODB_HOST}
      username: ${MONGODB_USERNAME}


#      mongodb+srv://pelumijsh:Oluwapelumi@cluster0:
#        7b2ybts:
#          mongodb:
##            net/?retryWrites=true&w=majority: