management:
  endpoints:
    web:
      exposure:
      include: '*'
  info:
    env:
      enabled: true

info:
  application:
    name: Perry Logistics
    description: Online platform where customer can send and receive goods.
    author: PerryJay
    version: '@project.version@'
spring:
  profiles:
    active: prod
