management:
  endpoints:
    web:
      exposure:
      include: '*'
  info:
    env:
      enabled: true

info:
  application:
    name: CapstoneHotels
    description: An hotel website where guest can make room reservation
    author: PerryJay
    version: '@project.version@'
spring:
  profiles:
    active: prod

#spring.mail.host=localhost
#spring.mail.port=1025
#spring.mail.username=hello
#spring.mail.password=hello
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.ssl.trust="*"
#spring.mail.properties.mail.smtp.starttls.enable=true
#spring.mail.properties.mail.smtp.connectiontimeout=5000
#spring.mail.properties.mail.smtp.timeout=3000
#spring.mail.properties.mail.smtp.writetimeout=5000
