spring:
  mail:
    host: localhost
    port: 1025
    username: hello
    password: hello
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
          ssl:
            enable: true
            trust: "*"


#spring.mail.host=localhost
#spring.mail.port=1025
#spring.mail.username=hello
#spring.mail.password=hello
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.ssl.trust="*"
#spring.mail.properties.mail.smtp.starttls.enable=true
#spring.mail.properties.mail.smtp.connectiontimeout=5000
#spring.mail.properties.mail.smtp.timeout=3000
#spring.mail.properties.mail.smtp.writetimeout=5000
